Repository Woom-s-Land/wooms-frontend, pull requests merged in 2024-07, with the labels that each got.

#3 Config : 도커파일 설정
  Dockerfile
Labels: ⚙️ Config

#5 Config : package.json에 Script 추가
  package.json
Labels: ⚙️ Config

#7 Config : 도커컴포즈, Jenkinsfile 추가
  Jenkinsfile
  docker-compose.yml
Labels: ⚙️ Config

#12 Feat : 로그인 구현
  package-lock.json
  package.json
  src/App.jsx
  src/assets/logo/github.svg
  src/assets/logo/google.svg
  src/components/auth/Login.jsx
  src/components/auth/OauthHandler.jsx
  src/main.jsx
  src/store/authSlice.jsx
  src/store/store.jsx
Labels: ✨ Feature

#15 Feat: 개인 공간 맵 렌더링 및 캐릭터 이동
  package-lock.json
  src/App.jsx
  src/MainPage.jsx
  src/assets/char_1/char_1 (0_0).png
  src/assets/char_1/char_1 (0_1).png
  src/assets/char_1/char_1 (0_2).png
  src/assets/char_1/char_1 (0_3).png
  src/assets/char_1/char_1 (0_4).png
  src/assets/char_1/char_1 (0_5).png
  src/assets/char_1/char_1 (0_6).png
  src/assets/char_1/char_1 (0_7).png
  src/assets/char_1/char_1 (1_0).png
  src/assets/char_1/char_1 (1_1).png
  src/assets/char_1/char_1 (1_2).png
  src/assets/char_1/char_1 (1_3).png
  src/assets/char_1/char_1 (1_4).png
  src/assets/char_1/char_1 (1_5).png
  src/assets/char_1/char_1 (1_6).png
  src/assets/char_1/char_1 (1_7).png
  src/assets/char_1/char_1 (2_0).png
  src/assets/char_1/char_1 (2_1).png
  src/assets/char_1/char_1 (2_2).png
  src/assets/char_1/char_1 (2_3).png
  src/assets/char_1/char_1 (2_4).png
  src/assets/char_1/char_1 (2_5).png
  src/assets/char_1/char_1 (2_6).png
  src/assets/char_1/char_1 (2_7).png
  src/assets/char_1/char_1 (3_0).png
  src/assets/char_1/char_1 (3_1).png
  src/assets/char_1/char_1 (3_2).png
  src/assets/char_1/char_1 (3_3).png
  src/assets/char_1/char_1 (3_4).png
  src/assets/char_1/char_1 (3_5).png
  src/assets/char_1/char_1 (3_6).png
  src/assets/char_1/char_1 (3_7).png
  src/assets/home/forward_home.png
  src/assets/home/home-collisions.js
  src/assets/home/home.png
  src/utils/boundaryUtils.js
  src/world/CharacterInHome.jsx
  src/world/Home.jsx
  src/world/Nickname.jsx
  src/world/characterImages.js
  src/world/homeImages.js
Labels: ✨ Feature

#18 Feat: 개인 공간 객체 상호작용
  src/MainPage.jsx
  src/assets/home/home-interactions.js
  src/assets/home/home_active_bed.png
  src/assets/home/home_active_desk.png
  src/assets/home/home_active_toilet.png
  src/assets/home/interaction_key.png
  src/world/CharacterInHome.jsx
  src/world/Home.jsx
  src/world/InteractionSpeechBubble.jsx
  src/world/homeImages.js
Labels: ✨ Feature

#14 Feat: 회원가입 기능 구현
  src/App.jsx
  src/components/auth/Signup.jsx
Labels: ✨ Feature

#22 Bug: 캐릭터 이동 버그 수정
  src/assets/home/forward_home.png
  src/assets/home/home-collisions.js
  src/assets/home/home.png
  src/assets/home/home_active_bed.png
  src/assets/home/home_active_desk.png
  src/assets/home/home_active_toilet.png
  src/world/CharacterInHome.jsx
Labels: 🐛 Bug

#26 Feat: 그룹 공간 맵 렌더링 및 캐릭터 이동
  src/App.css
  src/App.jsx
  src/MainPage.jsx
  src/assets/map/map.png
  src/world/CharacterInMap.jsx
  src/world/Map.jsx
  src/world/mapImages.js
Labels: ✨ Feature

#31 Feat: 그룹 공간 충돌 처리
  src/assets/map/map_collisions.js
  src/world/CharacterInMap.jsx
  src/world/Map.jsx
Labels: ✨ Feature

#32 Feat: 그룹 공간 상호 작용 구현
  src/assets/map/map-interactions.js
  src/assets/map/map.png
  src/assets/map/map_interaction_guestbook.png
  src/assets/map/map_interaction_photo.png
  src/assets/map/map_interaction_photomap.png
  src/world/mapImages.js
Labels: ✨ Feature

#34 Feat: 임시 비밀번호 발급
  src/App.css
  src/App.jsx
  src/MainPage.jsx
  src/components/auth/Login.jsx
  src/components/auth/OauthHandler.jsx
  src/components/auth/PasswordReset.jsx
  src/components/common/Modal.jsx
Labels: ✨ Feature
