Repository Woom-s-Land/wooms-frontend, pull requests merged in 2024-08, with the labels that each got.

#50 Feat: 사연 작성 및 읽기 구현
  src/App.jsx
  src/MainPage.jsx
  src/assets/story/input-box-story.png
  src/components/groupSpace/story/StoryReadModal.jsx
  src/components/groupSpace/story/StoryWriteModal.jsx
  tailwind.config.js
Labels: ✨ Feature

#45 Feat: 방명록 컴포넌트 구현
  src/App.jsx
  src/MainPage.jsx
  src/assets/comment/dialoge-box.png
  src/assets/comment/input-box.png
  src/assets/profile/profile-1.png
  src/assets/profile/profile-2.png
  src/assets/profile/profile-3.png
  src/components/groupSpace/comment/CommentModal.jsx
Labels: ✨ Feature

#44 Chore: socket.io 라이브러리 설치
  package-lock.json
  package.json
Labels: 🍃 Chore

#39 Feat: 사용자 정보 변경
  src/App.jsx
  src/assets/common/eye_close.png
  src/assets/common/eye_open.png
  src/assets/dialog/dialog box big.png
  src/assets/dialog/dialog box medium.png
  src/assets/dialog/dialog box small.png
  src/assets/dialog/dialog box.png
  src/components/auth/Login.jsx
  src/components/auth/OauthHandler.jsx
  src/components/auth/Signup.jsx
  src/components/common/Button.jsx
  src/components/navbar/MyInfo.jsx
  src/components/navbar/PasswordChange.jsx
  src/index.css
  src/store/authSlice.jsx
Labels: ✨ Feature

#48 Feat: 그룹 생성 및 참가
  src/App.jsx
  src/MainPage.jsx
  src/assets/group/check.png
  src/assets/group/check_fill.png
  src/assets/group/copy.png
  src/assets/group/gr-btn-md-active.png
  src/assets/group/gr-btn-md.png
  src/assets/group/group-button-active.png
  src/assets/group/group-button.png
  src/assets/group/left-btn.png
  src/assets/group/right-btn.png
  src/components/common/Modal.jsx
  src/components/group/CreateGroup.jsx
  src/components/group/DetailButton.jsx
  src/components/group/Group.jsx
  src/components/group/GroupButton.jsx
  src/components/group/GroupList.jsx
  src/components/group/JoinGroup.jsx
  tailwind.config.js
Labels: ✨ Feature

#53 Feat: 사진 뒤집기 기능 구현
  src/components/groupSpace/photo/DetailModal.jsx
  src/components/groupSpace/photo/UploadModal.jsx
  src/world/characterImages.js
  tailwind.config.js
Labels: ✨ Feature

#58 Refactor: 내 정보 변경 화면 이미지 경로 수정
  src/components/navbar/MyInfo.jsx
  src/components/navbar/characterBasicImages.js
  src/store/authSlice.jsx
Labels: 🛠️ Refactor

#56 Refactor: 사진 컴포넌트 월별 표시 및 사진 크기 조정
  public/assets/image1.jpg
  public/assets/image2.jpg
  public/assets/image4.jpg
  public/assets/image7.jpg
  src/components/groupSpace/photo/DetailModal.jsx
  src/components/groupSpace/photo/ItemModal.jsx
  src/components/groupSpace/photo/PhotoModal.jsx
  src/components/groupSpace/photo/UploadModal.jsx
Labels: 🛠️ Refactor

#52 Feat: 편지 작성 기능
  src/App.jsx
  src/assets/common/drop_down_btn.png
  src/assets/common/normal_box.png
  src/assets/letter/letter.png
  src/components/common/DropDown.jsx
  src/components/common/ModalClose.jsx
  src/components/groupSpace/letter/ChooseDate.jsx
  src/components/groupSpace/letter/ChooseUser.jsx
  src/components/groupSpace/letter/MainLetter.jsx
  src/components/groupSpace/letter/WriteLetter.jsx
  src/index.css
Labels: ✨ Feature

#69 Bug: 캐릭터 속도 및 충돌 처리 버그
  src/assets/map/map_collisions.js
  src/world/CharacterInHome.jsx
  src/world/CharacterInMap.jsx
  src/world/InteractionSpeechBubble.jsx
  src/world/Nickname.jsx
Labels: 🐛 Bug

#72 Feat: 그룹 공간 상호작용 컴포넌트 연결
  src/components/common/Modal.jsx
  src/components/groupSpace/comment/CommentModal.jsx
  src/components/groupSpace/photo/DetailModal.jsx
  src/components/groupSpace/photo/ItemModal.jsx
  src/components/groupSpace/photo/PhotoModal.jsx
  src/components/groupSpace/photo/UploadModal.jsx
  src/components/groupSpace/photoHeatmap/PhotoHeatMap.jsx
  src/world/CharacterInMap.jsx
  src/world/Map.jsx
Labels: ✨ Feature

#62 Feat: 기본 로딩창 구현
  src/App.css
  src/App.jsx
  src/MainPage.jsx
  src/assets/common/spinner.gif
  src/components/common/Loading.jsx
Labels: ✨ Feature

#64 Feat#59 편지 조회 기능
  src/App.jsx
  src/assets/common/emptyHeart.png
  src/assets/common/fullHeart.png
  src/assets/common/miniSquareBtn.png
  src/assets/common/speechBubble.png
  src/components/groupSpace/letter/LetterDetail.jsx
  src/components/groupSpace/letter/LetterList.jsx
  src/components/groupSpace/letter/ReadLetterMain.jsx
  src/store/store.jsx
Labels: ✨ Feature

#87 Config: redux-persist 설정
  package-lock.json
  package.json
  src/main.jsx
  src/store/store.jsx
Labels: ⚙️ Config

#88 Feat: 그룹 공간 이동 라우팅 및 api 연결
  package-lock.json
  package.json
  src/App.jsx
  src/apis/GroupApi.js
  src/components/group/CreateGroup.jsx
  src/components/group/DetailButton.jsx
  src/components/group/Group.jsx
  src/components/group/GroupDetail.jsx
  src/components/group/GroupList.jsx
  src/components/group/JoinGroup.jsx
Labels: ✨ Feature

#90 Feat: 개인 공간 상호작용 연결
  src/components/common/Modal.jsx
  src/components/groupSpace/letter/ChooseUser.jsx
  src/components/groupSpace/letter/LetterList.jsx
  src/components/groupSpace/letter/MainLetter.jsx
  src/components/groupSpace/letter/ReadLetterMain.jsx
  src/world/CharacterInHome.jsx
  src/world/CharacterInMap.jsx
  src/world/Home.jsx
  src/world/InteractionSpeechBubble.jsx
Labels: ✨ Feature

#91 Refactor: 로그인, 회원가입
  src/components/auth/Login.jsx
  src/components/auth/OauthHandler.jsx
  src/components/auth/Signup.jsx
  src/components/groupSpace/letter/ReadLetterMain.jsx
Labels: 🛠️ Refactor

#97 Refactor: 로그아웃시 상태 변경 및 세션 초기화
  src/apis/LogoutApi.js
  src/store/authSlice.jsx
  src/store/store.jsx
Labels: 🛠️ Refactor

#95 Feat: 사진 변환 시 사용자 지정 팔레트 적용
  src/assets/photo/palette.json
  src/components/groupSpace/photo/UploadModal.jsx
  src/components/groupSpace/photo/custom/ColorButton.jsx
  src/components/groupSpace/photo/custom/ColorPaletteEditor.jsx
Labels: ✨ Feature

#101 Bug: Redux getDefaultMiddleware 수정
  src/store/store.jsx
Labels: 🐛 Bug

#110 Feat: 개인 공간에서 그룹 공간으로 이동
  src/assets/home/home-rug.png
  src/components/group/Group.jsx
  src/utils/homeImages.js
  src/utils/loadCharacterImages.js
  src/world/CharacterInHome.jsx
  src/world/Home.jsx
Labels: ✨ Feature

#111 Style : 메뉴 바 개선
  src/assets/menu/menu.png
  src/components/navbar/Menubar.jsx
  src/index.css
Labels: 🎀 Style

#113 Feat#98: bgm 재생
  package-lock.json
  package.json
  src/App.jsx
  src/components/bgm/BgmPlayer.jsx
  src/components/bgm/PlayBgm.jsx
  src/components/navbar/Menubar.jsx
  src/store/settingSlice.jsx
  src/store/store.jsx
Labels: ✨ Feature

#115 Remove: BgmPlayer import문 삭제
  src/components/navbar/Menubar.jsx
Labels: 🐛 Bug

#119 Feat: 그룹 기능 관련 api 연동
  src/apis/GroupApi.js
  src/assets/common/rolling.gif
  src/components/common/Error.jsx
  src/components/group/ButtonDetail.jsx
  src/components/group/ButtonDetailBlue.jsx
  src/components/group/ButtonDetailMenu.jsx
  src/components/group/ButtonGroup.jsx
  src/components/group/CreateGroup.jsx
  src/components/group/DetailButton.jsx
  src/components/group/DetailButtonBlue.jsx
  src/components/group/Group.jsx
  src/components/group/GroupDetail.jsx
  src/components/group/GroupList.jsx
  src/components/group/JoinGroup.jsx
Labels: ✨ Feature

#120 Feat : 그룹공간 그룹이름 표시
  index.html
  src/assets/group/group-title.png
  src/components/group/GroupList.jsx
  src/components/navbar/Menubar.jsx
  src/store/groupSlice.jsx
  src/store/store.jsx
  src/world/Map.jsx
  tailwind.config.js
Labels: ✨ Feature

#121 Refactor#118: 편지 관련 컴포넌트 리팩토링
  src/App.jsx
  src/assets/common/happyEmoji.png
  src/assets/common/sadEmoji.png
  src/assets/common/smileEmoji.png
  src/components/bgm/PlayBgm.jsx
  src/components/common/DropDown.jsx
  src/components/groupSpace/letter/ChooseDate.jsx
  src/components/groupSpace/letter/ChooseUser.jsx
  src/components/groupSpace/letter/LetterDetail.jsx
  src/components/groupSpace/letter/LetterList.jsx
  src/components/groupSpace/letter/ReadLetterMain.jsx
  src/components/groupSpace/letter/WriteLetter.jsx
  src/components/groupSpace/letter/WriteLetterMain.jsx
  src/fonts/SSShinb7Regular.ttf
  src/index.css
  src/world/Home.jsx
Labels: 🛠️ Refactor

#124 Style : 그룹 title 배경 이미지 패딩 조정
  src/world/Map.jsx
Labels: 🎀 Style

#128 Feat: 채팅 기능 구현
  package-lock.json
  package.json
  src/App.jsx
  src/assets/common/inputEmoji.png
  src/components/groupSpace/ChatBox.jsx
Labels: ✨ Feature

#130 Bug: 이미지 import 경로 변경
  src/components/groupSpace/ChatBox.jsx
Labels: 🐛 Bug

#135 Refactor : 그룹이름, 메뉴바 통합
  src/assets/home/home-title.png
  src/components/navbar/Menubar.jsx
  src/world/Map.jsx
  tailwind.config.js
Labels: 🛠️ Refactor

#136 Refactor#131: 정보 변경 모달창 수정
  src/components/navbar/MyInfo.jsx
Labels: 🛠️ Refactor

#133 Feat: 사진 지도 api 연결
  src/apis/PhotoApi.js
  src/assets/heatmap/dot.png
  src/assets/heatmap/dot1_1.png
  src/assets/heatmap/dot1_2.png
  src/assets/heatmap/dot1_3.png
  src/assets/heatmap/dot1_4.png
  src/assets/heatmap/heatmap_bg.png
  src/assets/heatmap/refresh.png
  src/components/groupSpace/photoHeatmap/PhotoHeatMap.jsx
  src/components/groupSpace/photoHeatmap/basemap.js
  src/world/Map.jsx
  tailwind.config.js
Labels: ✨ Feature

#138 Refactor : 메뉴바 디자인 수정
  src/components/navbar/Menubar.jsx
Labels: 🛠️ Refactor

#140 Style : 캐릭터 머리 에셋 추가
  src/assets/0/h1.png
  src/assets/1/h1.png
  src/assets/10/h1.png
  src/assets/11/h1.png
  src/assets/2/h1.png
  src/assets/3/h1.png
  src/assets/4/h1.png
  src/assets/5/h1.png
  src/assets/6/h1.png
  src/assets/7/h1.png
  src/assets/8/h1.png
  src/assets/9/h1.png
  src/components/navbar/Menubar.jsx
Labels: 🎀 Style

#142 Feat: 그룹 공간 채팅 적용
  src/components/groupSpace/ChatBox.jsx
  src/world/Map.jsx
Labels: ✨ Feature

#144 style: 마우스 커서 이미지 변경 전체 적용 및 conflict 해결
  package-lock.json
  package.json
  src/App.jsx
  src/assets/cursor/MouseBasic.png
  src/assets/cursor/MouseHold.png
  src/assets/cursor/MousePoint.png
  src/components/auth/Login.jsx
  src/components/common/Button.jsx
  src/components/common/DropDown.jsx
  src/components/common/Modal.jsx
  src/components/groupSpace/letter/ChooseUser.jsx
  src/components/groupSpace/letter/LetterDetail.jsx
  src/components/groupSpace/letter/WriteLetter.jsx
  src/components/groupSpace/letter/WriteLetterMain.jsx
  src/index.css
  tailwind.config.js
Labels: 🎀 Style

#145 Feat: 그룹 공간 라디오 연결
  src/assets/map/map-radio.png
  src/components/groupSpace/comment/CommentModal.jsx
  src/components/groupSpace/photoHeatmap/calculateMap.js
  src/components/groupSpace/radio/StoryReadModal.jsx
  src/components/groupSpace/radio/StoryWriteModal.jsx
  src/utils/mapImages.js
  src/world/CharacterInHome.jsx
  src/world/CharacterInMap.jsx
  src/world/Home.jsx
  src/world/Map.jsx
Labels: ✨ Feature

#147 Design: 편지 상세, 편지 쓰기 디자인 수정
  src/components/groupSpace/letter/LetterDetail.jsx
  src/components/groupSpace/letter/WriteLetter.jsx
Labels: 🎀 Style

#149 Feat : 그룹 이동 시 토큰 값 추가
  src/components/group/GroupList.jsx
Labels: ✨ Feature

#151 Refactor : 그룹 이동 토큰 추가 함수 수정
  src/apis/GroupApi.js
  src/components/group/GroupList.jsx
Labels: 🛠️ Refactor

#161 Feat : api 요청 성공, 실패 Alert
  src/apis/GroupSpaceApi.js
  src/components/common/Alert.jsx
  src/components/groupSpace/comment/CommentModal.jsx
  src/index.css
  src/main.jsx
  src/store/alertSlice.jsx
  src/store/store.jsx
Labels: ✨ Feature

#164 Style: 메인, 로그인, 회원가입 페이지 디자인 변경
  src/MainPage.jsx
  src/assets/cursor/MouseBasic.png
  src/assets/cursor/MousePoint.png
  src/assets/logo/imgLogo.png
  src/assets/logo/letterLogo.png
  src/assets/mainPage/IntroImg1.png
  src/assets/mainPage/IntroImg2.png
  src/assets/mainPage/introImg3.png
  src/assets/mainPage/letterImg.png
  src/assets/mainPage/photoMapImg.png
  src/components/auth/Login.jsx
  src/components/auth/Signup.jsx
  src/components/navbar/MyInfo.jsx
  vite.config.js
Labels: 🎀 Style

#167 Bug: 이미지 이름 변경 -> 이미지 불러오기 실패 해결
  public/assets/image1.jpg
  public/assets/image10.jpg
  public/assets/image11.jpg
  public/assets/image12.jpg
  public/assets/image13.jpg
  public/assets/image14.jpg
  public/assets/image15.jpg
  public/assets/image16.jpg
  public/assets/image17.jpg
  public/assets/image18.jpg
  public/assets/image19.jpg
  public/assets/image2.jpg
  public/assets/image20.jpg
  public/assets/image21.jpg
  public/assets/image22.jpg
  public/assets/image23.jpg
  public/assets/image24.jpg
  public/assets/image3.jpg
  public/assets/image4.jpg
  public/assets/image5.jpg
  public/assets/image6.jpg
  public/assets/image7.jpg
  public/assets/image8.jpg
  public/assets/image9.jpg
  src/components/auth/Signup.jsx
Labels: 🐛 Bug

#170 Bug: 이미지 이름 및 경로 변경
  src/MainPage.jsx
  src/assets/mainPage/firstImg.png
  src/assets/mainPage/secondImg.png
  src/assets/mainPage/thirdImg.png
Labels: 🐛 Bug

#171 Feat: 그룹 채팅 및 여러 캐릭터 이동 구현
  generateImageImports.js
  package-lock.json
  package.json
  src/assets/common/emoji.png
  src/characterImages.js
  src/components/groupSpace/ChatBox.jsx
  src/libs/socket/client.js
  src/world/CharacterInHome.jsx
  src/world/CharacterInMap.jsx
  src/world/Characters.jsx
  src/world/Map.jsx
Labels: ✨ Feature

#172 Bug: 편지 버그 수정
  src/components/groupSpace/letter/ChooseUser.jsx
  src/components/groupSpace/letter/LetterList.jsx
  src/components/groupSpace/letter/WriteLetterMain.jsx
Labels: 🐛 Bug

#175 Bug: 상호작용, 채팅, 캐릭터 움직임 분리
  src/components/common/Modal.jsx
  src/components/groupSpace/ChatBox.jsx
  src/world/CharacterInMap.jsx
  src/world/Home.jsx
  src/world/Map.jsx
Labels: 🐛 Bug

#177 Feat: 그룹 공간에서 개인 공간으로 이동
  src/components/navbar/MenuButton.jsx
  src/components/navbar/Menubar.jsx
  src/index.css
Labels: ✨ Feature

#182 Bug: 이모지 버튼 z-index 수정
  src/components/groupSpace/ChatBox.jsx
Labels: 🐛 Bug

#185 Feat: 그룹원 캐릭터 정보 표시 및 그룹 이름 hover 액션
  src/components/group/GroupList.jsx
  src/components/group/MemberInfo.jsx
Labels: ✨ Feature

#187 Design: 방명록 CSS 수정
  src/components/groupSpace/comment/CommentModal.jsx
Labels: 🎀 Style

#188 Bug: 내 정보 변경창 이미지 로드 및 변경 요청 오류
  src/components/navbar/MyInfo.jsx
  src/components/navbar/PasswordChange.jsx
Labels: 🐛 Bug

#190 Feat : 사용자 인증 체크 HOC 적용
  src/App.jsx
  src/components/auth/Login.jsx
  src/components/navbar/Menubar.jsx
  src/hoc/Auth.jsx
  src/world/Map.jsx
Labels: ✨ Feature

#191 Design: 메인페이지 로고, 소개 이미지 변경
  src/MainPage.jsx
  src/assets/logo/realLogo.png
  src/assets/mainPage/finalImg.png
  src/assets/mainPage/introMap.png
  src/components/auth/Signup.jsx
Labels: 🎀 Style

#197 Feat: 그룹 공간 라디오 충돌 처리
  src/assets/map/map_collisions.js
Labels: ✨ Feature

#198 Feat : 그룹 공간 접근 제한 적용
  src/hoc/Auth.jsx
Labels: ✨ Feature

#201 Refactor: alet 수정
  src/components/groupSpace/photo/UploadModal.jsx
  src/components/groupSpace/radio/StoryWriteModal.jsx
Labels: 🛠️ Refactor

#204 Feat : 공통 예외 메시지 추가
  src/apis/GroupSpaceApi.js
  src/components/common/Alert.jsx
  src/world/Characters.jsx
Labels: ✨ Feature

#206 Feat: 상호작용 키 알림
  src/assets/home/interaction_key.png
  src/assets/home/key-home.png
  src/assets/home/key-letter.png
  src/assets/map/key-radio.png
  src/utils/homeImages.js
  src/utils/mapImages.js
  src/world/Home.jsx
  src/world/Map.jsx
Labels: ✨ Feature

#208 Bug : 그룹 간 이동 불가 해결
  src/apis/LogoutApi.js
  src/components/group/GroupList.jsx
  src/components/navbar/Menubar.jsx
  src/hoc/Auth.jsx
  src/world/Map.jsx
Labels: 🐛 Bug

#211 Bug: 그룹 리스트 반환 버그 해결
  src/components/group/Group.jsx
Labels: 🐛 Bug

#214 Refactor: 편지 API 호출 예외 알람 처리
  src/components/groupSpace/letter/ChooseDate.jsx
  src/components/groupSpace/letter/ChooseUser.jsx
  src/components/groupSpace/letter/LetterDetail.jsx
  src/components/groupSpace/letter/LetterList.jsx
  src/components/groupSpace/photoHeatmap/PhotoHeatMap.jsx
Labels: 🛠️ Refactor

#215 Style: 메인 페이지 이미지 변경
  src/MainPage.jsx
  src/assets/mainPage/photoImg.png
  src/assets/mainPage/radioImg.png
Labels: 🎀 Style

#217 Style: 개인 공간 화면 변경
  src/assets/map/map-all.png
  src/components/navbar/Menubar.jsx
  src/world/Home.jsx
  tailwind.config.js
Labels: 🎀 Style

#219 Feat: 그룹, 개인 공간 이동 로딩 페이지 구현
  src/assets/common/loading_bus.gif
  src/components/auth/Login.jsx
  src/components/common/LoadingBus.jsx
  src/components/group/GroupList.jsx
  src/components/navbar/Menubar.jsx
  src/store/settingSlice.jsx
  src/world/Home.jsx
  src/world/Map.jsx
Labels: ✨ Feature

#222 Style: 개인 공간 gif 객체 추가
  src/assets/animation/aquarium/aquarium.js
  src/assets/animation/aquarium/aquarium1.png
  src/assets/animation/aquarium/aquarium2.png
  src/assets/animation/aquarium/aquarium3.png
  src/assets/animation/aquarium/aquarium4.png
  src/assets/animation/aquarium/aquarium5.png
  src/assets/animation/aquarium/aquarium6.png
  src/assets/animation/aquarium/aquarium7.png
  src/assets/animation/aquarium/aquarium8.png
  src/assets/animation/aquarium/aquarium9.png
  src/world/CharacterInHome.jsx
  src/world/CharacterInMap.jsx
  src/world/Home.jsx
Labels: 🎀 Style

#224 Bug: useSelector 중복 import
  src/world/Home.jsx
Labels: 🐛 Bug

#226 Refactor: 편지 삭제 시 API 호출 추가
  src/components/groupSpace/letter/LetterList.jsx
Labels: 🛠️ Refactor

#230 Refactor : 사용자 인증, 사진관, 방명록 예외 처리
  src/components/auth/Login.jsx
  src/components/groupSpace/comment/CommentModal.jsx
  src/components/groupSpace/photo/DetailModal.jsx
  src/components/groupSpace/photo/ItemModal.jsx
  src/components/groupSpace/photo/PhotoModal.jsx
  src/components/groupSpace/photo/UploadModal.jsx
  src/components/groupSpace/radio/StoryReadModal.jsx
  src/components/groupSpace/radio/StoryWriteModal.jsx
Labels: 🛠️ Refactor

#233 Feat: 채팅 말풍선 기능 구현
  src/components/groupSpace/ChatBox.jsx
  src/world/CharacterInMap.jsx
  src/world/Characters.jsx
  src/world/Map.jsx
  src/world/SpeechBubble.jsx
Labels: ✨ Feature

#234 Style: 그룹 공간 gif 객체 추가
  src/assets/animation/fish-shadow/fish-shadow1.png
  src/assets/animation/fish-shadow/fish-shadow10.png
  src/assets/animation/fish-shadow/fish-shadow11.png
  src/assets/animation/fish-shadow/fish-shadow12.png
  src/assets/animation/fish-shadow/fish-shadow13.png
  src/assets/animation/fish-shadow/fish-shadow14.png
  src/assets/animation/fish-shadow/fish-shadow15.png
  src/assets/animation/fish-shadow/fish-shadow2.png
  src/assets/animation/fish-shadow/fish-shadow3.png
  src/assets/animation/fish-shadow/fish-shadow4.png
  src/assets/animation/fish-shadow/fish-shadow5.png
  src/assets/animation/fish-shadow/fish-shadow6.png
  src/assets/animation/fish-shadow/fish-shadow7.png
  src/assets/animation/fish-shadow/fish-shadow8.png
  src/assets/animation/fish-shadow/fish-shadow9.png
  src/assets/animation/fish-shadow/fishShadow.js
  src/assets/animation/fountain/fountain.js
  src/assets/animation/fountain/fountain1.png
  src/assets/animation/fountain/fountain2.png
  src/assets/animation/fountain/fountain3.png
  src/assets/animation/fountain/fountain4.png
  src/assets/animation/seagullpeck/seagull1.png
  src/assets/animation/seagullpeck/seagull2.png
  src/assets/animation/seagullpeck/seagull3.png
  src/assets/animation/seagullpeck/seagullPeck.js
  src/assets/animation/seagulltakeoff/seagull1.png
  src/assets/animation/seagulltakeoff/seagull2.png
  src/assets/animation/seagulltakeoff/seagullTakeoff.js
  src/assets/animation/sql/sql.js
  src/assets/animation/sql/sql1.png
  src/assets/animation/sql/sql2.png
  src/assets/animation/sqr/sqr.js
  src/assets/animation/sqr/sqr1.png
  src/assets/animation/sqr/sqr2.png
  src/assets/animation/waterdrop/waterDrop.js
  src/assets/animation/waterdrop/waterdrop1.png
  src/assets/animation/waterdrop/waterdrop2.png
  src/assets/animation/waterdrop/waterdrop3.png
  src/assets/animation/waterdrop/waterdrop4.png
  src/assets/animation/waterdrop/waterdrop5.png
  src/assets/animation/waterdrop/waterdrop6.png
  src/assets/animation/waterdrop/waterdrop7.png
  src/assets/animation/waterleaf/leaf1.png
  src/assets/animation/waterleaf/leaf2.png
  src/assets/animation/waterleaf/leaf3.png
  src/assets/animation/waterleaf/leaf4.png
  src/assets/animation/waterleaf/waterLeaf.js
  src/assets/map/map-board.png
  src/assets/map/map.png
  src/components/groupSpace/photoHeatmap/checkPixelNumber.js
  src/world/CharacterInMap.jsx
  src/world/FishShadow.jsx
  src/world/Map.jsx
  src/world/RandomWaterDrops.jsx
  src/world/WaterDrop.jsx
  src/world/WaterLeaf.jsx
Labels: 🎀 Style

#235 Refactor: 편지지 모달창, 알람 최상단 렌더링 수정
  index.html
  src/assets/mainPage/letterImg.png
  src/components/common/Alert.jsx
  src/components/groupSpace/letter/LetterDetail.jsx
  src/components/groupSpace/letter/WriteLetter.jsx
Labels: 🛠️ Refactor

#239 Bug: 내 정보 수정 후 미반영 버그 해결
  src/world/Home.jsx
  src/world/Map.jsx
Labels: 🐛 Bug
